import { Header } from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900">
        <Sidebar/>
        <div className="ml-80 relative h-screen">
          <Header />
          
          <div className="py-24 max-w-4xl px-8 mx-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
